// MyBankCCOM.idl : IDL source for MyBankCCOM
//

// This file will be processed by the MIDL tool to
// produce the type library (MyBankCCOM.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(fed0c2f3-0b42-40bb-aae9-d1f510c6ac0d),
	dual,
	nonextensible,
	pointer_default(unique)
]

interface IMyBankATL : IDispatch
{
	[id(1)] HRESULT Login([in] BSTR username, [in] BSTR password, [out, retval] INT* token);
	[id(2)] HRESULT NewUser([in] INT token, [in] BSTR username, [in] BSTR password);
	[id(3)] HRESULT ListAccounts([in] INT token, [out, retval] BSTR* Accountdesc);
	[id(4)] HRESULT Logout([in] INT token);
	[id(5)] HRESULT NewAccount([in] INT token, [in] BSTR username, [in] BSTR description, [out, retval] INT* accountNumber);
	[id(6)] HRESULT PayInto([in] INT token, [in] INT accountNumber, [in] FLOAT amount);
	[id(7)] HRESULT Transfer([in] INT token, [in] INT fromAccountNumber, [in] INT toAccountNumber, [in] FLOAT amount, [in] BSTR comment);
	[id(8)] HRESULT Statement([in] INT token, [in] INT accountNumber, [in] BOOL detailed, [out, retval] BSTR* statement);
	[id(9)] HRESULT GetError([out, retval] BSTR* error);
};
[
	uuid(3feedad1-8c16-4a85-9440-b24d37ddfa2f),
	version(1.0),
]
library MyBankCCOMLib
{
	importlib("stdole2.tlb");
	[
		uuid(e96db8ed-48d8-47ae-b9d6-9cdf447ccc57)
	]
	coclass MyBankATL
	{
		[default] interface IMyBankATL;
	};
};

import "shobjidl.idl";
